name: timetable
description: A Flutter application for Time Table for students

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.8.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Services
  url_launcher: ^6.0.17
  shared_preferences: ^2.0.11
#  flutter_datetime_picker: ^1.4.0
#  android_alarm_manager: ^0.4.5+11
#  flutter_local_notifications: ^1.4.4+4
  http: ^0.13.4
  path_provider: ^2.0.8
  rxdart: ^0.27.3

  # Firebase Services
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.7
  firebase_messaging: ^11.2.6
  firebase_core: ^1.12.0



  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-VariableFont_wght.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf