name: timetable
description: A Flutter application for Time Table for students

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Services
  url_launcher: ^5.5.0
  shared_preferences: ^0.5.10
  flutter_datetime_picker: ^1.4.0
#  android_alarm_manager: ^0.4.5+11
  flutter_local_notifications: ^1.4.4+4
  http: ^0.12.0+4
  path_provider: ^1.6.1
  rxdart: ^0.23.1

  # Firebase Services
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  firebase_messaging: ^6.0.16

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-VariableFont_wght.ttf
